// Helpers for the client-portal session token persisted in localStorage.
// The token is opaque (random hex) generated by the `client-auth-login` edge function
// and validated server-side via SHA-256 hash in `client_sessions`.

export interface StoredClientSession {
  clientId: string;
  email?: string | null;
  phone?: string | null;
  sessionToken?: string | null;
  sessionExpiresAt?: string | null;
  savedAt?: string;
}

export function clientSessionKey(slug: string): string {
  return `client_portal_session:${slug}`;
}

export function readClientSession(slug: string): StoredClientSession | null {
  try {
    const raw = localStorage.getItem(clientSessionKey(slug));
    if (!raw) return null;
    return JSON.parse(raw) as StoredClientSession;
  } catch {
    return null;
  }
}

export function writeClientSession(slug: string, value: StoredClientSession): void {
  localStorage.setItem(clientSessionKey(slug), JSON.stringify(value));
}

export function clearClientSession(slug: string): void {
  localStorage.removeItem(clientSessionKey(slug));
}

/** Returns the active session token across any salon stored in localStorage. */
export function findAnyClientSessionToken(): string | null {
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      if (!k || !k.startsWith("client_portal_session:")) continue;
      const raw = localStorage.getItem(k);
      if (!raw) continue;
      try {
        const obj = JSON.parse(raw) as StoredClientSession;
        if (obj?.sessionToken) return obj.sessionToken;
      } catch { /* ignore */ }
    }
  } catch { /* ignore */ }
  return null;
}
