project_id = "gdjlajktmjskhpugzinh"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-data]
verify_jwt = false

[functions.stripe-sync]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.chat-ai-agent]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.establishment-ai-assistant]
verify_jwt = false
